[project]
name = "health-checker-mcp"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = []

[tool.uv.workspace]
members = [
    "apps/api-python",
]
